<?php

declare(strict_types=1);

namespace Mollie\Api\Types;

enum BusinessCategory: string
{
    case PetShops = 'PET_SHOPS';
    case VeterinaryServices = 'VETERINARY_SERVICES';
    case AcAndHeatingContractors = 'AC_AND_HEATING_CONTRACTORS';
    case CarpentryContractors = 'CARPENTRY_CONTRACTORS';
    case ElectricalContractors = 'ELECTRICAL_CONTRACTORS';
    case EquipmentToolsFurnitureRentalLeasing = 'EQUIPMENT_TOOLS_FURNITURE_RENTAL_LEASING';
    case GeneralContractors = 'GENERAL_CONTRACTORS';
    case SpecialTradeContractors = 'SPECIAL_TRADE_CONTRACTORS';
    case CharityAndDonations = 'CHARITY_AND_DONATIONS';
    case FundraisingCrowdfundingSocialService = 'FUNDRAISING_CROWDFUNDING_SOCIAL_SERVICE';
    case Apps = 'APPS';
    case BooksMediaMoviesMusic = 'BOOKS_MEDIA_MOVIES_MUSIC';
    case Games = 'GAMES';
    case SoftwareAndSubscriptions = 'SOFTWARE_AND_SUBSCRIPTIONS';
    case ChildCareServices = 'CHILD_CARE_SERVICES';
    case CollegesUniversities = 'COLLEGES_UNIVERSITIES';
    case ElementarySecondarySchools = 'ELEMENTARY_SECONDARY_SCHOOLS';
    case OtherEducationalServices = 'OTHER_EDUCATIONAL_SERVICES';
    case VocationalSchoolsTradeSchools = 'VOCATIONAL_SCHOOLS_TRADE_SCHOOLS';
    case AmusementParks = 'AMUSEMENT_PARKS';
    case EventTicketing = 'EVENT_TICKETING';
    case GamingEstablishments = 'GAMING_ESTABLISHMENTS';
    case MovieTheatres = 'MOVIE_THEATRES';
    case MusiciansBandsOrchestras = 'MUSICIANS_BANDS_ORCHESTRAS';
    case OnlineGambling = 'ONLINE_GAMBLING';
    case OtherEntertainmentRecreation = 'OTHER_ENTERTAINMENT_RECREATION';
    case SportingRecreationalCamps = 'SPORTING_RECREATIONAL_CAMPS';
    case SportsForecasting = 'SPORTS_FORECASTING';
    case CreditCounsellingRepair = 'CREDIT_COUNSELLING_REPAIR';
    case DigitalWallets = 'DIGITAL_WALLETS';
    case InvestmentServices = 'INVESTMENT_SERVICES';
    case MoneyServices = 'MONEY_SERVICES';
    case MortgagesInsurancesLoansFinancialAdvice = 'MORTGAGES_INSURANCES_LOANS_FINANCIAL_ADVICE';
    case SecurityBrokersDealers = 'SECURITY_BROKERS_DEALERS';
    case TrustOffices = 'TRUST_OFFICES';
    case VirtualCryptoCurrencies = 'VIRTUAL_CRYPTO_CURRENCIES';
    case Caterers = 'CATERERS';
    case FastFoodRestaurants = 'FAST_FOOD_RESTAURANTS';
    case FoodProductStores = 'FOOD_PRODUCT_STORES';
    case RestaurantsNightlife = 'RESTAURANTS_NIGHTLIFE';
    case BoatRentalsLeasing = 'BOAT_RENTALS_LEASING';
    case CruiseLines = 'CRUISE_LINES';
    case Lodging = 'LODGING';
    case PropertyRentalsCamping = 'PROPERTY_RENTALS_CAMPING';
    case Marketplaces = 'MARKETPLACES';
    case DentalEquipmentSupplies = 'DENTAL_EQUIPMENT_SUPPLIES';
    case DentistsOrthodontists = 'DENTISTS_ORTHODONTISTS';
    case MedicalServices = 'MEDICAL_SERVICES';
    case DrugPharmaciesPrescription = 'DRUG_PHARMACIES_PRESCRIPTION';
    case MedicalDevices = 'MEDICAL_DEVICES';
    case MedicalOrganizations = 'MEDICAL_ORGANIZATIONS';
    case MentalHealthServices = 'MENTAL_HEALTH_SERVICES';
    case Nursing = 'NURSING';
    case OpticiansEyeglasses = 'OPTICIANS_EYEGLASSES';
    case SocialAssociations = 'SOCIAL_ASSOCIATIONS';
    case MembershipFeeBasedSports = 'MEMBERSHIP_FEE_BASED_SPORTS';
    case OtherMembershipOrganizations = 'OTHER_MEMBERSHIP_ORGANIZATIONS';
    case AdultContentServices = 'ADULT_CONTENT_SERVICES';
    case CounselingServices = 'COUNSELING_SERVICES';
    case DatingServices = 'DATING_SERVICES';
    case HealthBeautySpas = 'HEALTH_BEAUTY_SPAS';
    case LandscapingServices = 'LANDSCAPING_SERVICES';
    case LaundryDrycleaningServices = 'LAUNDRY_DRYCLEANING_SERVICES';
    case MassageParlours = 'MASSAGE_PARLOURS';
    case OtherPersonalServices = 'OTHER_PERSONAL_SERVICES';
    case PhotographyStudios = 'PHOTOGRAPHY_STUDIOS';
    case SalonsBarbers = 'SALONS_BARBERS';
    case PoliticalParties = 'POLITICAL_PARTIES';
    case AccountingAuditingBookkeepingTaxPreparationServices = 'ACCOUNTING_AUDITING_BOOKKEEPING_TAX_PREPARATION_SERVICES';
    case AdvertisingServices = 'ADVERTISING_SERVICES';
    case CleaningMaintenanceJanitorialServices = 'CLEANING_MAINTENANCE_JANITORIAL_SERVICES';
    case ComputerRepair = 'COMPUTER_REPAIR';
    case Consultancy = 'CONSULTANCY';
    case SecurityServices = 'SECURITY_SERVICES';
    case DirectMarketing = 'DIRECT_MARKETING';
    case FuneralServices = 'FUNERAL_SERVICES';
    case GovernmentServices = 'GOVERNMENT_SERVICES';
    case HostingVpnServices = 'HOSTING_VPN_SERVICES';
    case IndustrialSuppliesNotElsewhereClassified = 'INDUSTRIAL_SUPPLIES_NOT_ELSEWHERE_CLASSIFIED';
    case LegalServicesAttorneys = 'LEGAL_SERVICES_ATTORNEYS';
    case MotionPicturesDistribution = 'MOTION_PICTURES_DISTRIBUTION';
    case OtherBusinessServices = 'OTHER_BUSINESS_SERVICES';
    case PrintingPublishing = 'PRINTING_PUBLISHING';
    case RealEstateAgents = 'REAL_ESTATE_AGENTS';
    case SanitationPolishingSpecialtyCleaning = 'SANITATION_POLISHING_SPECIALTY_CLEANING';
    case OfficeSupplies = 'OFFICE_SUPPLIES';
    case TestingLaboratoriesNotMedical = 'TESTING_LABORATORIES_NOT_MEDICAL';
    case TrainingAndCoaching = 'TRAINING_AND_COACHING';
    case Utilities = 'UTILITIES';
    case ReligiousOrganizations = 'RELIGIOUS_ORGANIZATIONS';
    case ClothingShoesAccessories = 'CLOTHING_SHOES_ACCESSORIES';
    case CommercialArt = 'COMMERCIAL_ART';
    case BeautyProducts = 'BEAUTY_PRODUCTS';
    case BooksPeriodicalsNewspapers = 'BOOKS_PERIODICALS_NEWSPAPERS';
    case HomeImprovement = 'HOME_IMPROVEMENT';
    case GiftsShops = 'GIFTS_SHOPS';
    case CbdMarijuanaProducts = 'CBD_MARIJUANA_PRODUCTS';
    case CoffeeShops = 'COFFEE_SHOPS';
    case ConvenienceStores = 'CONVENIENCE_STORES';
    case GiftCards = 'GIFT_CARDS';
    case EroticToys = 'EROTIC_TOYS';
    case Florists = 'FLORISTS';
    case FuelDealers = 'FUEL_DEALERS';
    case FurnitureFurnishingsEquipmentStores = 'FURNITURE_FURNISHINGS_EQUIPMENT_STORES';
    case GameToyHobbyShops = 'GAME_TOY_HOBBY_SHOPS';
    case OutdoorEquipment = 'OUTDOOR_EQUIPMENT';
    case HomeElectronics = 'HOME_ELECTRONICS';
    case HouseholdApplianceStores = 'HOUSEHOLD_APPLIANCE_STORES';
    case JewelryWatchClockAndSilverwareStoresUnder1000 = 'JEWELRY_WATCH_CLOCK_AND_SILVERWARE_STORES_UNDER_1000';
    case MusicStores = 'MUSIC_STORES';
    case OtherMerchandise = 'OTHER_MERCHANDISE';
    case LiquorStores = 'LIQUOR_STORES';
    case PaidTelevisionRadio = 'PAID_TELEVISION_RADIO';
    case PreciousStonesMetalsJewelryOver1000 = 'PRECIOUS_STONES_METALS_JEWELRY_OVER_1000';
    case RepairShops = 'REPAIR_SHOPS';
    case SecondHandStores = 'SECOND_HAND_STORES';
    case SportingGoodsSpecialtyRetailShops = 'SPORTING_GOODS_SPECIALTY_RETAIL_SHOPS';
    case SupplementsStores = 'SUPPLEMENTS_STORES';
    case TelecomEquipment = 'TELECOM_EQUIPMENT';
    case TelecomServices = 'TELECOM_SERVICES';
    case TobaccoProducts = 'TOBACCO_PRODUCTS';
    case TradersDiamonds = 'TRADERS_DIAMONDS';
    case TradersGold = 'TRADERS_GOLD';
    case WeaponsAmmunition = 'WEAPONS_AMMUNITION';
    case CommuterTransportation = 'COMMUTER_TRANSPORTATION';
    case CourierServices = 'COURIER_SERVICES';
    case OtherTransportationServices = 'OTHER_TRANSPORTATION_SERVICES';
    case Ridesharing = 'RIDESHARING';
    case TravelServices = 'TRAVEL_SERVICES';
    case AutomotivePartsAccessories = 'AUTOMOTIVE_PARTS_ACCESSORIES';
    case CarTruckCompanies = 'CAR_TRUCK_COMPANIES';
    case AutomotiveServices = 'AUTOMOTIVE_SERVICES';
    case BicyclePartsShopsService = 'BICYCLE_PARTS_SHOPS_SERVICE';
    case CarBoatCamperMobileHomeDealer = 'CAR_BOAT_CAMPER_MOBILE_HOME_DEALER';
    case CarRentals = 'CAR_RENTALS';
    case MotorcyclePartsShopsAndDealers = 'MOTORCYCLE_PARTS_SHOPS_AND_DEALERS';

    /**
     * @return list<string>
     */
    public static function all(): array
    {
        return array_map(fn (self $case) => $case->value, self::cases());
    }
}
