name: Build Scoped Mollie SDK Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --no-scripts --no-progress

      - name: Install PHP-Scoper
        run: |
          composer global require humbug/php-scoper
          echo "${HOME}/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Create scoper config
        run: |
          cat > scoper.inc.php <<EOF
          <?php
          return [
              'prefix' => 'MollieVendor',
              'finders' => [],
              'exclude-namespaces' => ['Mollie\\Api'],
              'exclude-files' => [],
          ];
          EOF

      - name: Scope dependencies
        run: php-scoper add-prefix --output-dir=./build/scoped

      - name: Setup autoloader
        run: |
          cd build/scoped
          composer dump-autoload --classmap-authoritative

          # Create a simple test script to verify the autoloader works
          cat > test_autoloader.php <<EOF
          <?php
          /*
           * Make sure to disable the display of errors in production code!
           */
          ini_set('display_errors', '1');
          ini_set('display_startup_errors', '1');
          error_reporting(E_ALL);

          require_once __DIR__ . "/vendor/autoload.php";

          /*
           * Initialize the Mollie API client to verify autoloading works
           */
          \$mollie = new \Mollie\Api\MollieApiClient();
          echo "Autoloader verification successful.\n";
          EOF

          # Run the test script
          php test_autoloader.php

          # Swap autoloader files to handle both scoped and non-scoped classes
          mv vendor/autoload.php vendor/composer-autoload.php
          sed -i.bak 's/autoload.php/composer-autoload.php/g' vendor/scoper-autoload.php
          mv vendor/scoper-autoload.php vendor/autoload.php
          rm vendor/*.bak

      - name: Create release zip
        run: |
          cd build/scoped
          zip -r ../../mollie-api-php_build_scoped_${{ github.event.release.tag_name }}.zip .
          cd ../..

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: mollie-api-php_build_scoped_${{ github.event.release.tag_name }}.zip
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
